### ISSUE TITLE
Can't compile on OSX

### ISSUE THREAD

**Issue by ladislas** [flavray/escape#22]
When trying to compile on OS X, I get the following error

```
Executable /Users/ladislas/dev/tmp/build-escape-Desktop_Qt_5_5_1_clang_64bit-Release/escape.app/Contents/MacOS/escape does not exist.
```

**Comment by flavray** [comment]
That's weird, this works like a charm on my OS X machine.
Do you use QtCreator or the raw console to build the project? I only tested with the console, I could dig a bit deeper if you have issues with QtCreator :-)

**Comment by Thooms** [comment]
@ladislas I deduce from the executable path that you're indeed using some Qt IDE, could you give here the version of Qt, OpenGL, and your IDE so we can fix your issue (_and_ fix it on GNU/Linux btw :) ) ?

**Comment by ladislas** [comment]
Yep, I'm using the ide.

It's the latest version of Qt and the IDE. I'm on OSX El  Capitan so it's OpenGL 4.1

**Comment by flavray** [comment]
I tried building using QtCreator, it works on my machine.

We developed the app using Qt 4.8.7, the latest version is 5.5, maybe that's the problem.

**Comment by ladislas** [comment]
ahhh! sure it is! I'll try with the 4.8 version

**Comment by ladislas** [comment]
I got it to work with Qt 4.8

great game but it's not easy...

**Comment by flavray** [comment]
\o/ Great!
